### ISSUE TITLE
Windows run is broken - shutil copy

### ISSUE THREAD

**Issue by electricitybender** [ukaea/powerbalance#21]
```
$ poetry run powerbalance run
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\apetrov\GitLab\powerbalance\power_balance\cli\__init__.py", line 63, in run
    pbm_session.pbm_main(*args, **kwargs)
  File "C:\Users\apetrov\GitLab\powerbalance\power_balance\cli\session.py", line 69, in pbm_main
    pbm_instance = pbm_core.PowerBalance(
  File "C:\Users\apetrov\GitLab\powerbalance\power_balance\core.py", line 158, in __init__
    self.pydelica_session = pydelica.Session(_pde_ll)
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\pydelica\__init__.py", line 37, in __init__
    self._compiler = Compiler()
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\pydelica\compiler.py", line 32, in __init__
    self._library = LibrarySetup()
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\pydelica\options.py", line 44, in __init__
    self._copy_libraries()
  File "C:\Users\apetrov\AppData\Local\pypoetry\Cache\virtualenvs\power-balance-s94LjY4y-py3.8\lib\site-packages\pydelica\options.py", line 55, in _copy_libraries
    shutil.copytree(library, _dest, symlinks=True)
  File "c:\users\apetrov\appdata\local\programs\python\python38\lib\shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "c:\users\apetrov\appdata\local\programs\python\python38\lib\shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\ReferenceResults\\Dymola\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesOneUTube_NegativeResistance.txt', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\ReferenceResults\\Dymola\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesOneUTube_NegativeResistance.txt', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\ReferenceResults\\\\Dymola\\\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesOneUTube_NegativeResistance.txt'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\ReferenceResults\\Dymola\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\ReferenceResults\\Dymola\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\ReferenceResults\\\\Dymola\\\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\ReferenceResults\\Dymola\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_HeatTransfer_ThermalResponseFactors_Validation_FiniteLineSource_Integrand_BoreholeLength.txt', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\ReferenceResults\\Dymola\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_HeatTransfer_ThermalResponseFactors_Validation_FiniteLineSource_Integrand_BoreholeLength.txt', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\ReferenceResults\\\\Dymola\\\\Buildings_Fluid_Geothermal_Borefields_BaseClasses_HeatTransfer_ThermalResponseFactors_Validation_FiniteLineSource_Integrand_BoreholeLength.txt'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.ConvectionResistanceCircularPipe.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.ConvectionResistanceCircularPipe.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.ConvectionResistanceCircularPipe.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.InternalResistancesOneUTubeNegative.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.InternalResistancesOneUTubeNegative.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.InternalResistancesOneUTubeNegative.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.InternalResistancesTwoUTubeNegative.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.InternalResistancesTwoUTubeNegative.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.InternalResistancesTwoUTubeNegative.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.MultipoleThermalResistances_OneUTube.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.MultipoleThermalResistances_OneUTube.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.MultipoleThermalResistances_OneUTube.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.MultipoleThermalResistances_TwoUTube.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.MultipoleThermalResistances_TwoUTube.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.Validation.MultipoleThermalResistances_TwoUTube.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.CylindricalHeatSource_Integrand.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.CylindricalHeatSource_Integrand.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.CylindricalHeatSource_Integrand.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_BoreholeLength.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_BoreholeLength.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_BoreholeLength.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.GFunction_1borehole_5meters.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.GFunction_1borehole_5meters.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.GFunction_1borehole_5meters.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.GFunction_SmallScaleValidation.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.GFunction_SmallScaleValidation.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.GFunction_SmallScaleValidation.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyExteriorWallWithWindowExteriorShade.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyExteriorWallWithWindowExteriorShade.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyExteriorWallWithWindowExteriorShade.mos'"), ('C:\\Users\\apetrov\\AppData\\Local\\Programs\\OpenModelica1.16.2\\lib\\omlibrary\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyExteriorWallWithWindowInteriorShade.mos', 'C:\\Users\\apetrov\\AppData\\Local\\Temp\\tmpkflwcg9r\\Buildings 6.0.0\\Resources\\Scripts\\OpenModelica\\compareVars\\Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyExteriorWallWithWindowInteriorShade.mos', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\apetrov\\\\AppData\\\\Local\\\\Programs\\\\OpenModelica1.16.2\\\\lib\\\\omlibrary\\\\Buildings 6.0.0\\\\Resources\\\\Scripts\\\\OpenModelica\\\\compareVars\\\\Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.SampledModel.OnlyExteriorWallWithWindowInteriorShade.mos'")]
```

**Comment by electricitybender** [comment]
Windows run now works, but some libraries (Buildings 6.0.0/7.0.0 and one other) will throw this error. Not a PBM issue - probably PyDelica.
